#!/bin/bash
-rwxr-xr-x 1 996 992 16 0-current_working_directory
-rw-r--r-- 1 996 992 11 1-lisit
-rwxr-xr-x 1 996 992 15 1-listit
-rw-r--r-- 1 996 992 18 2-bring_me_home
-rw-r--r-- 1 996 992 18 3-listfiles
-rw-r--r-- 1 996 992 74 README.md
